mixed-port: 7890
mode: rule
#allow-lan: true

external-controller: 0.0.0.0:7788
secret: "510510510"
external-ui: /app/mihomo/ui

tun:
  enable: true
  stack: system
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  nameserver:
    - 223.6.6.6
    - 223.5.5.5

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "BAN-US"
      - "DMIT-US"

proxies:
  - name: "BAN-US"
    type: http
    server: BAN-US.com
    port: 443
    username: username
    password: "password"
    tls: true
    skip-cert-verify: false
  - name: "DMIT-US"
    type: http
    server: DMIT-US.com
    port: 443
    username: username
    password: "password"
    tls: true
    skip-cert-verify: false

rule-providers:
  local:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/tongwoo/wall/main/mihomo/rules/local.yaml"
    path: ./providers/local.yaml
    interval: 3600
    proxy: PROXY

  develop:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/tongwoo/wall/main/mihomo/rules/develop.yaml"
    path: ./providers/develop.yaml
    interval: 3600
    proxy: PROXY

  ai:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/tongwoo/wall/main/mihomo/rules/ai.yaml"
    path: ./providers/ai.yaml
    interval: 3600
    proxy: PROXY

  ai-flow:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/tongwoo/wall/main/mihomo/rules/ai-flow.yaml"
    path: ./providers/ai-flow.yaml
    interval: 3600
    proxy: PROXY

  other:
    type: http
    behavior: classical
    format: yaml
    url: "https://raw.githubusercontent.com/tongwoo/wall/main/mihomo/rules/other.yaml"
    path: ./providers/other.yaml
    interval: 3600
    proxy: PROXY

  ad:
    type: http
    behavior: domain
    format: yaml
    url: "https://anti-ad.net/clash.yaml"
    path: ./providers/ad.yaml
    interval: 3600
    proxy: PROXY

rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - RULE-SET,ad,REJECT
  - RULE-SET,ai,PROXY
  - RULE-SET,ai-flow,PROXY
  - RULE-SET,develop,PROXY
  - RULE-SET,other,PROXY
  - RULE-SET,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT

  - GEOIP,CN,DIRECT
  #- MATCH,DIRECT
  - MATCH,PROXY
